# Generated by Django 4.2.7 on 2024-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('starting_cash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ending_cash', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
