# Generated by Django 4.2.7 on 2024-03-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashHandling', '0003_endingcash_startingcash_delete_cashdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('starting_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ending_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EndingCash',
        ),
        migrations.DeleteModel(
            name='StartingCash',
        ),
    ]
