# Generated by Django 4.2.7 on 2024-03-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashHandling', '0004_cashregister_delete_endingcash_delete_startingcash'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndCashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('ending_cash', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StartCashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('starting_cash', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CashRegister',
        ),
    ]
