# Generated by Django 4.2.5 on 2024-03-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CashHandling', '0006_cashentry_delete_endcashregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='ending_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='starting_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
