# Generated by Django 4.2.7 on 2024-03-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('week', models.IntegerField(unique=True)),
                ('month', models.IntegerField(unique=True)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_transactions', models.IntegerField()),
            ],
        ),
    ]
