# Generated by Django 4.2.7 on 2024-01-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='paymenttype',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
