# Generated by Django 4.2.7 on 2024-01-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_billingdetails_delete_customer_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='transactionid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
