# Generated by Django 4.2.7 on 2024-02-27 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0004_alter_billingdetails_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
