# Generated by Django 4.2.7 on 2024-03-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0005_billingdetails_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='transaction_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
